// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mnhhkkpygrsiqpyqqyix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1uaGhra3B5Z3JzaXFweXFxeWl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTc4ODIsImV4cCI6MjA2MDEzMzg4Mn0.fFuwDHfkVq2l2WUcPTI1SHTpO3FPQhNvTAXjqZ2YxTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);